### ISSUE TITLE
support xyz format or not?

### ISSUE THREAD

**Issue by zhangfq-chemistry** [molinfo-vienna/CDPKit#12]
Excellent project!

**Comment by seidelt** [comment]
Thank you!!

Regarding support for the XYZ format: I can easily implement it, shouldn't be a big deal. Give me a few days....

**Comment by seidelt** [comment]
Hi,
CDPKit now fully supports reading (including atom connectivity and bond order perception) and writing XYZ-files. Give it a try!

**Comment by zhangfq-chemistry** [comment]
Thanks!
