### ISSUE TITLE
Cannot open benzene.xyz format as follows

### ISSUE THREAD

**Issue by zhangfq-chemistry** [molinfo-vienna/CDPKit#14]
12
benzene 
C  -0.80396474    1.25550659   0.00000000
C   0.59119526    1.25550659   0.00000000
C   1.28873326    2.46325759   0.00000000
C   0.59107926    3.67176659   0.00000000
C  -0.80374574    3.67168859   0.00000000
C  -1.50134674    2.46348259   0.00000000
H  -1.35372374    0.30318959   0.00000000
H   1.14070326    0.30299359   0.00000000
H   2.38841326    2.46333759   0.00000000
H   1.14127926    4.62390959   0.00000000
H  -1.35386774    4.62396959   0.00000000
H  -2.60095074    2.46366559   0.00000000

**Comment by seidelt** [comment]
The last atom line is missing an end of line character (\n). When the file ends at a new line it works. Anyway, I have now made the reader more tolerant in this regard and ending at a new new line is not mandatory anymore. Give it a try, reading your data should work now!

**Comment by seidelt** [comment]
Closing fixed issue due to lack of further activity
