### ISSUE TITLE
Confgen has duplicated arg names

### ISSUE THREAD

**Issue by DrrDom** [molinfo-vienna/CDPKit#15]
The current of version `confgen` has two `-p` arguments
```
-p [ –fixed-substr-min-atoms ] arg
-p [ –progress ] [=arg(=1)]
```

**Comment by seidelt** [comment]
Hi Pavel,

many thanks for reporting! 'p' (–fixed-substr-min-atoms) has been replaced by '~'. I am running out letters, therefore the awkward symbol....
