### ISSUE TITLE
Does this excellent project support cif (crystallographic information file) or not ? Thanks!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [molinfo-vienna/CDPKit#16]

**Comment by zhangfq-chemistry** [comment]
Thanks!

**Comment by seidelt** [comment]
CDPKit now fully supports reading/writing data in mmCIF format!
If you use CDPKit's functionality via Python on Linux  then you can already use this new feature by installing the CDPKit V1.2.0 pre-release deposited on PyPI.

The pre-release can be installed as follows:
$ pip install CDPKit==1.2.0.dev1
