### ISSUE TITLE
How to use the CDPKit to caculate the number of ligand-based pharmacophore features

### ISSUE THREAD

**Issue by c799** [molinfo-vienna/CDPKit#2]
I tried to use a python script to calculate the potential pharmacophore characteristics of ligand, 
[error1.txt](https://github.com/molinfo-vienna/CDPKit/files/10895404/error1.txt)
But there is an error reported.

Boost.Python.ArgumentError: Python argument types in
    DefaultPharmacophoreGenerator.__init__(DefaultPharmacophoreGenerator, bool)
did not match C++ signature:

I don't know how to solve this problem, I hope to get help

Here are the details of the python script
import sys
import os.path as path
import CDPL.Pharm as Pharm
import CDPL.Math as Math
import CDPL.Chem as Chem
import CDPL.Base as Base
import numpy
from collections import Counter

def count_features():
    if len(sys.argv) < 2:
        print >> sys.stderr, 'Usage:', sys.argv[0], '[input.sdf]'
        sys.exit(2)
    ifs = Base.FileIOStream(sys.argv[1], 'r')

    ligand = Chem.BasicMolecule()
    sdf_reader = Chem.SDFMoleculeReader(ifs)

    lig_pharm = Pharm.BasicPharmacophore()
    pharm_gen = Pharm.DefaultPharmacophoreGenerator(True)
    ftr_list = list()

    while sdf_reader.read(ligand):
        Chem.perceiveSSSR(ligand, True)
        Chem.setAromaticityFlags(ligand, False)
        Chem.setRingFlags (ligand, False)
        pharm_gen.generate(ligand, lig_pharm)
        ftr_list += [Pharm.getType(ftr) for ftr in lig_pharm]
    
    with open("feature_count.txt", "w+") as writer:
        writer.write(str(dict(Counter(ftr_list))))
    
if __name__ == '__main__':
    count_features()

**Comment by seidelt** [comment]
Sorry for that! The apo2ph4 code is based on an older version of CDPKit and the Pharm.DefaultPharmacophoreGenerator constructor has changed in the meantime. Replacing 'pharm_gen = Pharm.DefaultPharmacophoreGenerator(True)' by 'pharm_gen = Pharm.DefaultPharmacophoreGenerator()' should fix the problem!

**Comment by seidelt** [comment]
Sorry again, the constructor call is not the only thing that has to be changed. I have adapted 'count_features.py' in the apo2ph4 repository to work with the current CDPKit version...

**Comment by c799** [comment]
Thank you for your response. After making the modifications to the script, all errors have been resolved and the new script runs successfully.
