### ISSUE TITLE
Inconsistent style in the tag of SDF output file

### ISSUE THREAD

**Issue by gkxiao** [molinfo-vienna/CDPKit#5]
In the SDF output file, there are inconsistent style of the property tags.

**Comment by seidelt** [comment]
Unfortunately, the description of the problem observed is not very detailed. However, I found a bug in the SD-block output code that causes the indentation of property tags to grow. The bug has been fixed now and I hope this will eliminate the issue.

**Comment by seidelt** [comment]
Closed due to lack of activity...
