### ISSUE TITLE
Conformer generation with restrictions

### ISSUE THREAD

**Issue by DrrDom** [molinfo-vienna/CDPKit#6]
Hello Thomas,
my congratulations with the release of CDPKit!
I'm interested in enumeration of conformers where a part of atoms have fixed pre-defined 3D coordinates and positions of only some atoms are sampled. Is it possible to perform in CDPKit from Python? It seems not, because I could not find something relevant in the documentation, but maybe I missed something.
Kind regards,
Pavel

**Comment by seidelt** [comment]
Hi Pavel,

thank you, better late than never ;-)

Conforge does not yet provide a built-in option to do this  (but I intend to implement such functionality which will then be released with next minor CDPKit  version update). However, with a bit of programming it can be done already. Until next week I can provide you with a Python script that takes a molecule 3D structure and a SMARTS pattern specifying the fixed substructure as input, performs torsion driving on the given 3D structure (ignoring rotatable bonds belonging to the fixed part), and then writes the generated conformers to an output file.

Would such a script fulfill your needs?

@Documentation: It is still in a quite early stage and A LOT is left to be done here.....

Best regards,
Thomas

PS: Next week you will give a talk at my department, right?

**Comment by DrrDom** [comment]
Thank you! Such an example would be useful for me and maybe other users. However there is no hurry.
Yes, next week I'll be at your department, so we may discuss this issue next week in person :)

**Comment by seidelt** [comment]
Perfect, I will then add the script to the Python cookbook and thus make it available for other interested users.... Looking forward to your talk next week!

**Comment by seidelt** [comment]
Hi Pavel,

I have finished the promised script and it works as desired! It's called 'tor_drive.py' and can be found in the CDPKit sources  sub-folder 'Examples/Python'. Please execute the script with the '-h' option to get info about required/supported options and their arguments. To install the CDPKit python bindings simply do a 'pip install cdpkit'. If you have any questions -> don't hesitate to ask!

**Comment by DrrDom** [comment]
Probably I do something wrong

I created a 3D structure in chemaxon, used the following command and got an error. It seems that an input molecule is not recognized as 3D, however, I do not see issues in SDF file.
```
python tor_drive.py -i 1.sdf -o 1_conf.sdf -f c1ccccc1 -a
- Generating conformers for molecule 'n1' (#1)...
 -> Found 1 fixed substructure pattern match(es)
Error: torsion driving or output of generated conformers for molecule 'n1' (#1) failed: Python argument types in
    None.None(BasicBond)
did not match C++ signature:
    None(CDPL::Chem::Atom {lvalue})
```
[1.sdf.txt](https://github.com/molinfo-vienna/CDPKit/files/13039273/1.sdf.txt)

If I correctly understood, the script takes input 3D molecules and a pattern, generates conformers keeping a part matched by a pattern fixed and then aligns all conformers to this fixed part.

For my particular task it would be more convenient to have a function which takes reference molecule as 3D and a list of input molecules (any format) and returns conformers of input molecules where a part matched to the reference molecule has the same coordinates as reference. Of course, in this case only one unique match should exist, otherwise it should produce an error or take a random match from the list.

I would see this as an extension of the basic function in this script https://cdpkit.org/v1.0.0/cdpl_python_cookbook/confgen/ensembles.html

Original
```
def genConfEnsemble(mol: Chem.Molecule, conf_gen: ConfGen.ConformerGenerator) -> (int, int):
```
Updated
```
def genConfEnsemble(mol: Chem.Molecule, refmol: Chem.Molecule, conf_gen: ConfGen.ConformerGenerator) -> (int, int):
```

**Comment by seidelt** [comment]
The latest version of the script works with fine with the provided example molecule and pattern. Maybe you used an older, still buggy version of the script (I have fixed a bug resulting in an error message like yours). Please retry with the current version of the script.

Regarding the described use case: If the input molecules for which to generate the conformers do not provide atom 3D coordinates things are getting much more complicated and require more programming effort. However, I plan to include the described feature in an upcoming Conforge version.

**Comment by DrrDom** [comment]
Hm, I downloaded the latest version from the master branch, the issue persists. I attached the script.
Other conformer generation scripts work well.
[tor_drive.py.txt](https://github.com/molinfo-vienna/CDPKit/files/13040367/tor_drive.py.txt)

**Comment by seidelt** [comment]
Sorry, indeed, you are using the latest script already. The mentioned bug that got fixed was in the Python wrapper C++ code not in the script itself, I mixed things up. It was only a minor issue but causes the script to fail with the CDPKit version on PyPI that you are using. I pushed a new version of the script that should work now also with the older CDPKit version you are using... Sorry for that!

**Comment by DrrDom** [comment]
I confirms, now it works as expected. Thank you!

**Comment by seidelt** [comment]
Glad to hear that, thank you for the confirmation!
