### ISSUE TITLE
score-only option results in that shapescreen gives wrong value

### ISSUE THREAD

**Issue by gkxiao** [molinfo-vienna/CDPKit#8]
- [x] I believe this to be a bug with shapescreen
- [ ] This is a feature request

## Environment Information
ShapeScreen version: V1.0.0 (C) Thomas Seidel,  Build: 202307120555
Operating system and version: Ubuntu 22 (Linux master 5.15.0-43-generic)

## Expected Behavior
<p>When we compare a  molecule to itself, the Tanimito shape similarity should be 1. </p>

## Actual Behavior
<p>Shapescreen give a shape similarity close to 0 which means no similarity.</p>

## Steps to Reproduce
Let me show you an example:
<img src="https://zinc.docking.org/substances/ZINC000012524304.png">
<p>Its 3D representation can be available here: <a href="http://8.210.229.141/ZINC12524304.sdf">ZINC12524304.sdf</a></p>
<p>Let's compare the shape of ZINC12524304 with itself:</p>
<pre line="1">
shapescreen -d ZINC12524304.sdf -q ZINC12524304.sdf -o score_only.sdf  -r score_only.rpt -t 1 --score-only true
</pre>
<p>From the report file,score_only_1.rpt, we can find that:</p>
<pre line="1">
Shape Tanimoto = 0.071
Color Tanimoto = 0.013
Tanimoto Combo = 0.084
</pre>
<p>The values of score are far away from 1.</p>

**Comment by seidelt** [comment]
Thank you for testing and reporting the erroneous behavior! The bug has been fixed in the master branch.
